#!/bin/bash
[ $# -eq 1 ] && [ -n "$1" ] || { echo "Usage: $0 /path/to/root/succinct" >&2; exit 2; }
cd "$1" || exit 1
[ -d config ] || { echo "config: directory not found" >&2; exit 1; }

[ -f config/config.vars ] && . config/config.vars

SUCCINCT_HOME="$PWD"
if [ -z "$TEXTMAGIC_CALLBACK_KEY" ]; then
    TEXTMAGIC_CALLBACK_KEY=$(dd if=/dev/random bs=8 count=1 status=none | sha256sum | awk '{print $1}')
    echo "Generated key for TextMagic: $TEXTMAGIC_CALLBACK_KEY"
fi
if [ -z "$ROCK_CALLBACK_KEY" ]; then
    ROCK_CALLBACK_KEY=$(dd if=/dev/random bs=8 count=1 status=none | sha256sum | awk '{print $1}')
    echo "Generated key for Rock: $ROCK_CALLBACK_KEY"
fi
if [ -z "$DIRECT_API_KEY" ]; then
    DIRECT_API_KEY=$(dd if=/dev/random bs=8 count=1 status=none | sha1sum | awk '{print $1}')
    echo "Generated key for direct API access: $DIRECT_API_KEY"
fi

( echo "# automatically generated by update-config.sh"
  echo "# changes to this file will NOT take effect until update-config.sh is run again"
  echo "SUCCINCT_HOME=\"$SUCCINCT_HOME\""
  echo "TEXTMAGIC_CALLBACK_KEY=\"$TEXTMAGIC_CALLBACK_KEY\""
  echo "ROCK_CALLBACK_KEY=\"$ROCK_CALLBACK_KEY\""
  echo "DIRECT_API_KEY=\"$DIRECT_API_KEY\""
) > config/config.vars.new

mv config/config.vars.new config/config.vars

function sed_escape {
    printf %s "$1" | sed 's/[\/&]/\\&/g'
}

[ -e config/succinct-default.php ] || { echo "config/succinct-default.php: file not found" >&2; exit 1; }

sed "s/_SUCCINCT_HOME_/$(sed_escape "$SUCCINCT_HOME")/g; \
     s/_TEXTMAGIC_CALLBACK_KEY_/$(sed_escape "$TEXTMAGIC_CALLBACK_KEY")/g; \
     s/_DIRECT_API_KEY_/$(sed_escape "$DIRECT_API_KEY")/g; \
     s/_ROCK_CALLBACK_KEY_/$(sed_escape "$ROCK_CALLBACK_KEY")/g" config/succinct-default.php > config/succinct.new.php

if cmp -s config/succinct.new.php config/succinct.php; then
    echo "config/succinct.php: no changes"
    rm -f config/succinct.new.php
elif ! [ -f config/succinct.php ]; then
    echo "config/succinct.php: created from default template"
    diff -pdU4 config/succinct-default.php config/succinct.new.php
    mv config/succinct.new.php config/succinct.php
else
    echo "config/succinct.php: changed"
    diff -pdU4 config/succinct.php config/succinct.new.php
    mv config/succinct.new.php config/succinct.php
fi
